# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
    ]
