# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-21 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='text',
        ),
    ]
